### ISSUE TITLE
DashDB out node does not clear previous error message

### ISSUE THREAD

**Issue by tonykambo** [smchamberlin/node-red-contrib-ibm-db2#13]
If I have two dashDB out nodes in a flow and the first results in an error the msg.error message is passed into the second dashDB out node and is not cleared. The result is that after the second dashDB out node completes without an error the msg.error is still populated the with result from the first. 

For example:

http in->function->dashdb out 1->function->dashdb out 2->function->http response

An error on dashdb out 1 will flow into dashdb out 2 and even though dashdb out 2's result is not an error it will still have an error

**Comment by smchamberlin** [comment]
Fixed in latest push
