### ISSUE TITLE
Data insert stops randomly

### ISSUE THREAD

**Issue by MarcDorloechter** [smchamberlin/node-red-contrib-ibm-db2#17]
We are developing a NodeRED application for a customer. When using the dashDB output node dashDB, i.e. Db2 Warehouse on Cloud, suddenly stops inserting the data.
We have a JSON object with 171 rows. We see in the Debug node that all 171 rows arrive on the dashDB node. However, it is always a different number that is in fact written in dashDB. Sometimes it is 41, sometimes 50, sometimes 122, etc. So, the error is not captured by the Debug node.
Interestingly, we made the experience that directly after deploying my flow in Node-RED and first execution the dashDB nodes works correctly for the first time and write all 171 rows in the DB.

**Comment by smchamberlin** [comment]
Hi Marc, I believe we have communicated separately by email on this?

I also delivered some new code fixes today.

I will close this for now, please reopen if you continue to see issue with latest code.

Thanks.
