### ISSUE TITLE
Please pin ibm_db dependency

### ISSUE THREAD

**Issue by knolleary** [smchamberlin/node-red-contrib-ibm-db2#4]
Currently the ibm_deb dependency is set to 'x' - so the latest version will always be picked up.

They have published a new version that drops support for Node 0.10 and has broken the Node-RED boilerplate as we still list 0.10 as the required engine (something we'll be changing urgently now in response) - https://github.com/ibmdb/node-ibm_db/issues/88

Unfortunately they did so with only a minor version number change which is not proper semantic versioning. But had they done it properly, and had this package depended on 0.0.x, all would have been ok.

So we'd like this package to update its dependencies to 0.0.x (or 0.1.x if ibm_db republish their release with a proper version number bump...).

**Comment by smchamberlin** [comment]
Hi Nicholas -- I have temporarily "fixed" the Bluemix boilerplate by forcing downlevel version 0.0.17 of ibm_db in the package.json for node-red-nodes-cf-sqldb-dashdb

I will change it to 0.0.x after you have migrated the engine to newer Node version

**Comment by knolleary** [comment]
The boilerplate has been updated everywhere, but hold off for the moment until we see what ibm_dB do with their versioning, and I need to think through the impact on existing instances when they restage.

**Comment by smchamberlin** [comment]
Ok, will keep it at 0.0.17 until I receive notice from you

**Comment by bimalkjha** [comment]
This issue should be fixed now with ibm_db@0.0.19. But, please start using newer version of node.js. v 0.10.x is very old. Thanks.

**Comment by smchamberlin** [comment]
I put back 0.0.x for ibm_db dependency in the latest version just delivered.
